### ISSUE TITLE
Adapt plotting/post-processing scripts for v0.0.3 of the JSON files

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/acwf-verification-scripts#16]
v0.0.3 now includes the number of atoms in the simulation cells.

`generate_plots.py` has been adapted and plots quantities per formula unit.

Also the other plotting scripts need to be adapted for this! E.g.:
- histogram generation
- the Jupyter notebook

Moreover, one should check all points in the code where we assume the number of atoms.
E.g. in quantities_for_comparison, in the function delta_per_atom, we do the assumption of the number of atoms.

Finally: a good idea is to extract some functions from `generate_plots.py` to avoid copy-pasting (and thus errors). (Pinging @bosonie with whom we discussed this)

**Comment by bosonie** [comment]
This was resolved in [243ed3f](https://github.com/aiidateam/acwf-verification-scripts/commit/243ed3fc9459cf038cb9dcdab9104ce7701f575d)
