### ISSUE TITLE
jupiter notebook must be extended to work with unaries

### ISSUE THREAD

**Issue by bosonie** [aiidateam/acwf-verification-scripts#19]
So far, the [show-plots-GUI.ipynb](https://github.com/aiidateam/acwf-verification-scripts/blob/main/3-analyze/outputs/show-plots-GUI.ipynb) detects all the json files with "results-" string in the folder and makes them available for comparison.
However, this script only works for oxides. The results is that errors pops up when a "result-...json" containing unaries set is present in the folder!

**Comment by bosonie** [comment]
Partially resolved in [09c1785](https://github.com/aiidateam/acwf-verification-scripts/commit/09c178573e0d767c0fcf7c16371fd2a3a583aeca).
Now two different notebook are present, one for oxides, one for unaries. The selection of the "results-<>.json" to include in the comparison is based on the detection of the "unaries" string in the file name. Maybe fragile? 
Also did not test the export capabilities.

**Comment by giovannipizzi** [comment]
Fixed in #43
