### ISSUE TITLE
cif error with ase (replace CIF with XSF also for oxides)

### ISSUE THREAD

**Issue by DannyVanpoucke** [aiidateam/acwf-verification-scripts#22]
There appears to be an issue with the cif-format of all oxides (according to ase)
The following line:
_symmetry_Int_Tables_number      '1'
throws an error:
"ase.spacegroup.spacegroup.SpacegroupNotFoundError: invalid spacegroup `1`, setting `1` not found in data base".

The issue is resolved by removing the " ' "s
_symmetry_Int_Tables_number      1

**Comment by giovannipizzi** [comment]
Thanks. We are using pymatgen that has a more robust parser. But indeed probably the best will be to replace with XSF like for the unaries, for which the parsers are more robust

**Comment by giovannipizzi** [comment]
xsf added now
