### ISSUE TITLE
need to rename `mk2-castep` to just `castep`

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/acwf-verification-scripts#24]
In the data folder here: https://github.com/aiidateam/acwf-verification-scripts/tree/main/acwf_paper_plots/code-data

Should rename  `mk2-castep` to just `castep`.
This avoids confusion, as the default setting in the _common-workflows_ repository already uses update lanthanide/actinides potentials.

https://github.com/aiidateam/aiida-common-workflows/blob/bb9090a8bd8bc703ffaeda42b439dcfeebf55bf5/aiida_common_workflows/workflows/relax/castep/protocol.yml#L128

If the name of the pseudo potential should be included, `castep-c19mk2` is a better option.

**Comment by giovannipizzi** [comment]
Thanks! I'm merging #27 but also taking a note that we need to add the results-unaries-verification-PBE-v1-castep-PseudoDojo-0.4-PBE-SR-standard-utf.json and similar to the 'methods-supplementary'
